# Generated by Django 6.0.3 on 2026-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='connector_type',
            field=models.CharField(choices=[('TYPE2', 'Type 2'), ('CCS2', 'CCS2'), ('CHADEMO', 'CHAdeMO')], default='CCS2', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charger',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=60, help_text='Cost per kWh', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='charger_type',
            field=models.CharField(choices=[('L2', 'L2 Charger'), ('L3', 'L3 Fast Charger')], max_length=10),
        ),
    ]
