# Generated by Django 6.0.3 on 2026-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_charger_connector_type_charger_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_minutes',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
