# Generated by Django 6.0.3 on 2026-03-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
