# Generated by Django 6.0.3 on 2026-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chargingqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingqueue',
            name='priority_score',
            field=models.FloatField(default=0),
        ),
    ]
