# Generated by Django 6.0.3 on 2026-03-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chargingqueue_priority_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='connector_type',
            field=models.CharField(choices=[('TYPE1', 'Type 1'), ('TYPE2', 'Type 2'), ('CCS', 'CCS'), ('CCS2', 'CCS2'), ('CHADEMO', 'CHAdeMO')], max_length=20),
        ),
    ]
