# Generated by Django 6.0.3 on 2026-03-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='connector_type',
            field=models.CharField(choices=[('TYPE1', 'Type 1'), ('TYPE2', 'Type 2'), ('CCS', 'CCS'), ('CCS2', 'CCS2'), ('CHADEMO', 'CHAdeMO'), ('GBT', 'GBT')], max_length=20),
        ),
    ]
