# Generated by Django 6.0.3 on 2026-03-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_booking_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='connector',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
    ]
