# Generated by Django 6.0.3 on 2026-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_booking_amount_alter_booking_connector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='energy_used_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOPUP', 'Top Up'), ('HOLD', 'Hold Amount'), ('PAYMENT', 'Charging Payment'), ('REFUND', 'Refund')], max_length=20),
        ),
    ]
