# Generated by Django 6.0.3 on 2026-03-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
