# Generated by Django 6.0.3 on 2026-03-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_card_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='threshold',
            field=models.IntegerField(default=20),
        ),
    ]
